// What each industry page says that's specific to that industry: an example
// month of posts, the platforms that matter and what goes on each, the year's
// moments, the rules we follow, what we measure, which real work and case
// studies to show. Practical guidance only: no invented figures.
//
// cal: [day, format, idea, why it works] — four weeks of three posts.
// platforms: [name, role, [what we post…]] — most important first.
// year: twelve [moment, detail] — January first.
// rules / track: [title, text].
// work: portfolio filter (scripts/build-industries.js): industry, subs, an
//   optional caption pattern to keep (or drop) posts.
// cases: case study slugs (fx/cases.json), with the label shown above them.

module.exports = {
  'social-media-management-for-restaurants': {
    name: 'restaurants', noun: 'restaurant', people: 'diners', place: 'your tables',
    cal: [
      ['Mon', 'Reel', 'Dish of the week, plated in slow motion', 'Food Reels get saved and shared, which is how nearby diners find you.'],
      ['Wed', 'Carousel', 'This week’s specials', 'Gives regulars a reason to come back this week, not someday.'],
      ['Fri', 'Story', 'Weekend booking reminder with a link', 'Catches people deciding where to eat tonight.'],
      ['Mon', 'Reel', 'Behind the pass: Friday service in 15 seconds', 'The energy of a full room is the best ad for a table.'],
      ['Wed', 'Carousel', 'Meet the chef: where the menu comes from', 'People book places with a face and a story.'],
      ['Fri', 'Photo', 'Guest photo of the week (with their OK)', 'Real guests make the next guest feel welcome.'],
      ['Mon', 'Reel', 'How we make our signature dish', 'Process videos hold attention and build appetite.'],
      ['Wed', 'Carousel', 'What to drink with what: a pairing guide', 'Useful posts get saved, and saved posts get seen again.'],
      ['Fri', 'Story', 'Poll: which dish should come back?', 'Two taps of engagement that keep you in their feed.'],
      ['Mon', 'Reel', 'Our regulars’ favourite order', 'Social proof in the form of food.'],
      ['Wed', 'Photo', 'Private dining or event announcement', 'Fills the slower nights and bigger tables.'],
      ['Fri', 'Carousel', 'Your reviews, our thanks', 'Shows happy guests and thanks them in public.'],
    ],
    platforms: [
      ['Instagram', 'Where they decide where to eat', ['Dish and drink Reels', 'Stories with today’s specials', 'A pinned menu and booking link']],
      ['Google Business Profile', 'Where they book and get directions', ['Fresh food and room photos', 'Posts for specials and events', 'Accurate hours, and replies to every review']],
      ['TikTok', 'Where they discover somewhere new', ['Kitchen behind-the-scenes', 'Short “what we ate” style clips', 'Trends, done with your food']],
      ['Facebook', 'Where locals plan nights out', ['Events and live music', 'Private dining and catering', 'Posts that travel in local groups']],
    ],
    year: [
      ['Dry January', 'Lighter dishes and alcohol-free drinks'], ['Valentine’s Day', 'Set menus and early bookings'], ['Spring menu', 'Launch posts for new dishes'],
      ['Easter brunch', 'Family tables and brunch bookings'], ['Mother’s Day', 'One of the busiest booking days; patios open'], ['Summer menu', 'Father’s Day and longer evenings'],
      ['Outdoor dining', 'Patio, terrace and late sunsets'], ['Back to school', 'Family deals and weekday routines'], ['Autumn menu', 'Seasonal dishes and comfort food'],
      ['Halloween', 'Themed specials and events'], ['Holiday parties', 'Group bookings and Thanksgiving'], ['Gift cards & NYE', 'Holiday parties, gift cards, New Year’s Eve'],
    ],
    rules: [
      ['Allergens and dietary claims are exact', 'We only call a dish vegan, gluten-free or nut-free when you confirm it, and flag shared-kitchen risks the way you want.'],
      ['Alcohol is promoted responsibly', 'Drink posts follow the platforms’ alcohol policies and your local rules: aimed at adults, never at excess.'],
      ['Guests’ photos with permission', 'Guest photos and tags are shared only with their OK, and credited.'],
      ['Prices and specials stay current', 'Specials are dated and prices are real, so nobody turns up for an offer that ended.'],
    ],
    track: [
      ['Reservations and order clicks', 'Taps on your booking and ordering links, from each post.'],
      ['Directions and calls', 'Google Business Profile actions: people on their way to you.'],
      ['Saves and shares', 'The signal that food posts are doing their job.'],
      ['Local reach', 'How many people near you saw your posts this month.'],
      ['Reviews and mentions', 'New reviews, tags and guests posting about you.'],
    ],
    work: { ind: 'Food & Drink', subs: ['Restaurants & Bars', 'Food Products', 'Beverage Products'] },
    cases: { label: 'food and drink brands', slugs: ['a-pensive-mans-coffee', 'casa-m-spice-co', 'miss-sprinkles-gelato', 'district-raleigh'] },
  },

  'social-media-management-for-dentists': {
    name: 'dental practices', noun: 'practice', people: 'patients', place: 'your chairs',
    cal: [
      ['Mon', 'Reel', 'Meet the team: who you’ll see at your visit', 'Familiar faces take the nerves out of booking.'],
      ['Wed', 'Carousel', 'Five signs you’re brushing too hard', 'Useful tips get saved and shared with family.'],
      ['Fri', 'Story', 'Open check-up slots this week', 'A direct, low-effort nudge to book.'],
      ['Mon', 'Reel', 'Your first visit, step by step', 'Answers “what will happen?” before they ask.'],
      ['Wed', 'Photo', 'A patient’s smile story (with written consent)', 'Real outcomes, shared the right way.'],
      ['Fri', 'Carousel', 'Myth or fact: whitening', 'Clears up confusion and shows expertise.'],
      ['Mon', 'Reel', 'Tips for your child’s first dental visit', 'Speaks to the parent who books for the family.'],
      ['Wed', 'Carousel', 'Insurance and payment options, explained', 'Removes the most common reason people wait.'],
      ['Fri', 'Story', 'Ask the dentist: one question answered', 'Opens a conversation that often ends in a booking.'],
      ['Mon', 'Reel', 'Inside the practice: tech that makes visits easier', 'Shows a modern, comfortable practice.'],
      ['Wed', 'Photo', 'Team milestone or community event', 'Local practices win on being part of the community.'],
      ['Fri', 'Carousel', 'Thank you: this month’s reviews', 'Reviews are what new patients look for first.'],
    ],
    platforms: [
      ['Facebook', 'Where local families look', ['Practice news and opening hours', 'Patient-friendly tips', 'Community events and reviews']],
      ['Google Business Profile', 'Where they choose and book', ['Practice and team photos', 'Posts and Q&A', 'Replies to every review']],
      ['Instagram', 'Where they get to know you', ['Team and practice Reels', 'Smile stories, with consent', 'Stories with open slots']],
      ['YouTube Shorts', 'Where they look up treatments', ['Short treatment explainers', 'What to expect videos', 'Myth-busting clips']],
    ],
    year: [
      ['Benefits reset', 'New-year dental benefits: book cleanings early'], ['Children’s Dental Health Month', 'February in the US: family and kids’ content'], ['Spring smile', 'Whitening and smile refresh'],
      ['Oral Cancer Awareness Month', 'April: screenings and awareness'], ['Weddings & graduations', 'Smile makeovers before big days'], ['Summer schedules', 'Check-ups before holidays'],
      ['Sports season', 'Mouthguards and dental injuries'], ['Back to school', 'Check-ups before term starts'], ['Routine check-ups', 'Six-month reminders'],
      ['Dental Hygiene Month', 'October, plus Halloween candy tips'], ['Use it or lose it', 'Remind patients to use benefits before year-end'], ['Holiday hours', 'Opening times and last appointments'],
    ],
    rules: [
      ['Patient privacy first', 'No patient names, photos or details without written consent, in line with HIPAA.'],
      ['Replies that protect patients', 'We thank reviewers without confirming that they’re a patient or mentioning any treatment.'],
      ['Honest before-and-afters', 'Real, consented cases only, unedited, with no promise of results.'],
      ['Your dental board’s rules', 'Specialty titles and claims follow your state dental board’s advertising rules.'],
    ],
    track: [
      ['New-patient calls and requests', 'Calls, forms and messages that came from social.'],
      ['“Book” clicks', 'Taps on your booking link from posts, Stories and your profile.'],
      ['Google Business Profile actions', 'Calls, directions and website visits from your listing.'],
      ['Reviews', 'New reviews each month, and your replies.'],
      ['Questions in messages', 'People asking about treatments, prices or availability.'],
    ],
    // (These posts have no captions: the dental ones, picked by eye.)
    work: { ind: 'Health & Beauty', subs: ['Medical & Dental'], only: ["86a193deb3d6","d336ca039f55","9ef5d232892a","dbf77e84631e","c11ff6eb021d","8d83cd3d5f68","855c8787a66f","92a6c5d7285f","3b23730f22a8","bfd05fa48f1c","5155d8595084"] },
    cases: { label: 'healthcare practices', slugs: ['act-for-pain', 'psychology-in-the-park'] },
  },

  'social-media-management-for-gyms': {
    name: 'gyms and studios', noun: 'gym', people: 'members', place: 'your classes',
    cal: [
      ['Mon', 'Reel', 'Monday’s class in 20 seconds', 'Lets people picture themselves in the room.'],
      ['Wed', 'Carousel', 'Form fix: one move, three cues', 'The posts members save and send to friends.'],
      ['Fri', 'Story', 'Weekend schedule and free-trial link', 'Catches people making weekend plans.'],
      ['Mon', 'Reel', 'Member spotlight (with their OK)', 'Real members are more convincing than models.'],
      ['Wed', 'Carousel', 'Your first week here: a beginner’s guide', 'Answers the fears that stop people joining.'],
      ['Fri', 'Photo', 'Coach intro: who’ll train you', 'People join coaches, not just gyms.'],
      ['Mon', 'Reel', 'A workout to do at home this weekend', 'Useful content that keeps you in their feed.'],
      ['Wed', 'Carousel', 'Nutrition basics from our coaches', 'Shows expertise beyond the gym floor.'],
      ['Fri', 'Story', 'Poll: which new class should we add?', 'Members feel heard; you learn what they want.'],
      ['Mon', 'Reel', 'Challenge or event highlights', 'Community is what keeps members paying.'],
      ['Wed', 'Photo', 'Milestones: 100 classes, new PRs', 'Celebrates members and motivates everyone else.'],
      ['Fri', 'Carousel', 'Memberships and prices, explained', 'Answers the question that comes before signing up.'],
    ],
    platforms: [
      ['Instagram', 'Where they picture themselves training', ['Class and workout Reels', 'Coach intros and member stories', 'Stories with schedules and trial links']],
      ['TikTok', 'Where they look for workouts', ['Form tips and quick routines', 'Gym culture and humour', 'Challenges']],
      ['Facebook', 'Where the local community gathers', ['Events and challenges', 'Schedule changes', 'Member celebrations']],
      ['Google Business Profile', 'Where they compare gyms nearby', ['Photos of the space and classes', 'Offers and opening hours', 'Replies to reviews']],
    ],
    year: [
      ['New Year’s resolutions', 'The biggest sign-up month of the year'], ['Keep going', 'Challenges for when motivation dips'], ['Spring challenge', 'A fresh start, mid-season'],
      ['Summer-ready programmes', 'Start now for the summer'], ['Outdoor sessions', 'Bootcamps and outdoor classes'], ['Summer schedule', 'Holiday timetables and short programmes'],
      ['Bring a friend', 'Summer referral pushes'], ['Back to routine', 'After the holidays'], ['Back to school', 'New schedules, new members'],
      ['Autumn challenge', 'Plus Halloween-themed classes'], ['Beat the holiday slump', 'Stay consistent through the season'], ['Gift memberships', 'And New Year pre-sales'],
    ],
    rules: [
      ['Every face, with consent', 'Members are filmed and posted only with their permission.'],
      ['No promises of results', 'No guaranteed weight-loss figures; transformations are real and come with typical-results wording where needed.'],
      ['Music cleared for business', 'Reels use audio licensed for business accounts, so posts aren’t muted or taken down.'],
      ['Safe form on camera', 'Every exercise we post is checked by your coaches first.'],
    ],
    track: [
      ['Trial and class sign-ups', 'Bookings that started on social.'],
      ['Membership enquiries', 'Messages asking about prices, classes and joining.'],
      ['Local reach', 'People near you who saw your content this month.'],
      ['Saves on workout posts', 'The posts members keep and come back to.'],
      ['Tags and check-ins', 'Members posting from your gym.'],
    ],
    work: { ind: 'Health & Beauty', subs: ['Fitness & Gym', 'Yoga & Pilates', 'Sports & Recreation'] },
    cases: { label: 'fitness brands', slugs: ['ingrid-s-clay'] },
  },

  'social-media-management-for-law-firms': {
    name: 'law firms', noun: 'firm', people: 'clients', place: 'your calendar',
    cal: [
      ['Mon', 'Video', 'Myth vs. law: a common misconception in your practice area', 'Plain answers build trust before anyone calls.'],
      ['Wed', 'Carousel', 'What to bring to your first consultation', 'Makes the first step feel easy.'],
      ['Fri', 'Photo', 'Attorney profile: why they practise this law', 'People hire a person they feel they know.'],
      ['Mon', 'Video', 'One question answered in 30 seconds', 'The questions clients ask you every week, answered once for everyone.'],
      ['Wed', 'Carousel', 'How a case moves, step by step', 'Takes the fear out of the unknown.'],
      ['Fri', 'Story', 'Consultation availability', 'A clear, compliant next step.'],
      ['Mon', 'Video', 'A day at the firm', 'Shows the people behind the letterhead.'],
      ['Wed', 'Carousel', 'A law change, explained in plain English', 'Positions you as the local expert.'],
      ['Fri', 'Photo', 'Community involvement', 'Local firms are chosen by local people.'],
      ['Mon', 'Video', 'Common mistakes that hurt a claim', 'High-value advice that gets shared.'],
      ['Wed', 'Carousel', 'Five terms you’ll hear, explained', 'Useful, saveable, and easy to understand.'],
      ['Fri', 'Photo', 'Firm news: recognitions and new hires', 'Credibility for referral partners on LinkedIn.'],
    ],
    platforms: [
      ['LinkedIn', 'Where referrals and reputation build', ['Attorney insights and commentary', 'Firm news and recognitions', 'Legal updates for referral partners']],
      ['Google Business Profile', 'Where they choose a firm', ['Accurate practice areas and hours', 'Posts and Q&A', 'Replies to reviews']],
      ['Facebook', 'Where local clients look', ['Plain-English explainers', 'Community involvement', 'Consultation information']],
      ['YouTube', 'Where they research their problem', ['Explainer videos by your attorneys', 'FAQ videos', 'What-to-expect series']],
    ],
    year: [
      ['New-year checklists', 'Wills, contracts and planning'], ['Tax-season questions', 'Business and personal'], ['Business formation', 'Spring starts and contracts'],
      ['Tax deadline', 'Last-minute questions in April'], ['Law Day', 'May 1 in the US: explain a right'], ['Summer safety', 'Driving and accident awareness'],
      ['Mid-year check-up', 'Business legal health check'], ['Back to school', 'Custody schedules and family matters'], ['Labor Day', 'Workers’ rights explainers'],
      ['Estate planning week', 'Third week of October in the US'], ['Year-end planning', 'Deadlines before the new year'], ['Holiday hours', 'And year-end reminders'],
    ],
    rules: [
      ['Your bar’s advertising rules', 'Posts follow your state bar’s rules on attorney advertising, including any required labels and disclaimers.'],
      ['No promised outcomes', 'Past results carry the disclaimers your bar requires, and nothing implies a guaranteed result.'],
      ['No legal advice in comments', 'Comments and messages get a polite route to a consultation, never advice on someone’s case.'],
      ['Client confidentiality', 'No client details, ever, without written permission.'],
    ],
    track: [
      ['Consultation requests', 'Forms, calls and messages that came from social.'],
      ['Profile and website visits', 'From people in your area and practice areas.'],
      ['Reviews', 'New reviews each month, and your replies.'],
      ['Referral-partner engagement', 'Other professionals engaging with your LinkedIn content.'],
      ['Video views on explainers', 'Which questions people care about most.'],
    ],
    work: { ind: 'Professional Services', subs: ['Legal Services'] },
    cases: { label: 'professional services', slugs: ['client-b-high-acquisition-cost'] },
  },

  'social-media-management-for-medical': {
    name: 'medical practices', noun: 'practice', people: 'patients', place: 'your appointment book',
    cal: [
      ['Mon', 'Reel', 'Meet your care team', 'Patients choose clinicians they feel they know.'],
      ['Wed', 'Carousel', 'Doctor, urgent care or ER: which one?', 'Practical guidance people save and share.'],
      ['Fri', 'Story', 'Appointment availability this week', 'A simple, direct way to book.'],
      ['Mon', 'Reel', 'What to expect at your first visit', 'Lowers the barrier to booking.'],
      ['Wed', 'Carousel', 'A seasonal health tip from our clinicians', 'Timely, useful and on-brand.'],
      ['Fri', 'Photo', 'A patient story (with written consent)', 'Real experiences, shared the right way.'],
      ['Mon', 'Reel', 'Myth vs. fact on a common condition', 'Clear, trustworthy education.'],
      ['Wed', 'Carousel', 'Insurance and payment questions', 'Answers what stops people booking.'],
      ['Fri', 'Story', 'Ask us: general health questions', 'Starts conversations, routed to a visit.'],
      ['Mon', 'Reel', 'A tour of the clinic', 'Shows a calm, modern space.'],
      ['Wed', 'Carousel', 'This month’s health awareness theme', 'Ties your expertise to what people are hearing about.'],
      ['Fri', 'Photo', 'A community health event', 'Local care, visibly local.'],
    ],
    platforms: [
      ['Facebook', 'Where patients and families look', ['Clinic news and hours', 'Health tips', 'Community events']],
      ['Google Business Profile', 'Where they choose and book', ['Services and accurate hours', 'Photos of the clinic', 'Replies to reviews']],
      ['Instagram', 'Where they get to know your team', ['Team intros and clinic tours', 'Education Reels', 'Stories with availability']],
      ['YouTube', 'Where they research symptoms and treatments', ['Plain-English explainers by your clinicians', 'What-to-expect videos', 'FAQ series']],
    ],
    year: [
      ['New-year health goals', 'Check-ups and screenings'], ['Heart Month', 'February in the US'], ['Spring allergies', 'Seasonal symptoms'],
      ['Stress Awareness Month', 'April'], ['Mental Health Awareness Month', 'May'], ['Men’s Health Month', 'June'],
      ['Summer safety', 'Sun, heat and hydration'], ['Back-to-school', 'Physicals and vaccinations'], ['Flu-shot season', 'Booking reminders'],
      ['Breast Cancer Awareness Month', 'October'], ['Diabetes Awareness Month', 'November'], ['Winter health', 'Holiday stress and winter illnesses'],
    ],
    rules: [
      ['HIPAA-safe by default', 'No patient information without written authorisation, and nothing that could identify a patient.'],
      ['Education, not diagnosis', 'Posts give general information and point people to a visit, never individual advice.'],
      ['Claims your clinicians approve', 'Every health claim is reviewed by your team, and nothing promises an outcome.'],
      ['Health ad rules', 'Meta and Google limit how health ads can target people; campaigns are built within those limits.'],
    ],
    track: [
      ['Appointment requests', 'Bookings and messages that came from social.'],
      ['Calls and directions', 'Google Business Profile actions.'],
      ['Reviews', 'New reviews each month, and your replies.'],
      ['Engagement on education posts', 'Which topics patients want to hear about.'],
      ['New-patient sources', 'How new patients say they found you.'],
    ],
    work: { ind: 'Health & Beauty', subs: ['Medical & Dental', 'Physical Therapy', 'Mental Health'], not: ["86a193deb3d6","d336ca039f55","9ef5d232892a","dbf77e84631e","c11ff6eb021d","8d83cd3d5f68","855c8787a66f","92a6c5d7285f","3b23730f22a8","bfd05fa48f1c","5155d8595084","4414462cb9a2"] },
    cases: { label: 'healthcare practices', slugs: ['act-for-pain', 'psychology-in-the-park'] },
  },

  'social-media-management-for-real-estate': {
    name: 'real estate agents', noun: 'brokerage', people: 'buyers and sellers', place: 'your pipeline',
    cal: [
      ['Mon', 'Reel', 'New listing walkthrough', 'Video tours are what buyers stop scrolling for.'],
      ['Wed', 'Carousel', 'Neighbourhood guide: five local favourites', 'Sells the area, not just the house.'],
      ['Fri', 'Story', 'Open house this weekend', 'Turns interest into a visit.'],
      ['Mon', 'Reel', 'Just sold: the story behind the sale', 'Proof for sellers deciding who to list with.'],
      ['Wed', 'Carousel', 'Before you make an offer: a checklist', 'Useful for buyers, saved for later.'],
      ['Fri', 'Photo', 'Agent intro', 'People choose an agent before a house.'],
      ['Mon', 'Reel', 'The local market in 60 seconds', 'Positions you as the person who knows the area.'],
      ['Wed', 'Carousel', 'Getting your home ready to sell', 'Speaks to future sellers early.'],
      ['Fri', 'Story', 'Poll: which kitchen would you choose?', 'Easy engagement that keeps you visible.'],
      ['Mon', 'Reel', 'Keys handed over (with the buyers’ OK)', 'Happy clients are your best listing pitch.'],
      ['Wed', 'Carousel', 'Mortgage terms explained (with a lender partner)', 'Answers buyers’ biggest question.'],
      ['Fri', 'Photo', 'A local community event', 'Local presence builds referrals.'],
    ],
    platforms: [
      ['Instagram', 'Where buyers browse homes', ['Listing Reels and tours', 'Stories for open houses', 'Just-sold posts']],
      ['Facebook', 'Where local buyers and sellers talk', ['Listings and open houses', 'Neighbourhood content', 'Events']],
      ['YouTube', 'Where serious buyers research', ['Full home tours', 'Area guides', 'Market updates']],
      ['TikTok', 'Where first-time buyers learn', ['Buying tips', 'Quick tours', 'Myths about buying and selling']],
    ],
    year: [
      ['Planning to buy?', 'New-year goals and budgets'], ['Pre-approval season', 'Get ready before spring'], ['Spring listings', 'The market picks up'],
      ['Open-house season', 'Busy weekends'], ['Peak season', 'Listings and sold stories'], ['Summer moves', 'Before the school year'],
      ['Mid-year market update', 'Prices, stock, timing'], ['Neighbourhood guides', 'Schools and local life'], ['Autumn market', 'Second wind for sales'],
      ['Seller prep', 'List before the winter'], ['Year-end moves', 'Plus Thanksgiving'], ['Year in review', 'And thank-yous to clients'],
    ],
    rules: [
      ['Fair Housing in every post', 'No wording that suggests a preference for or against anyone based on a protected characteristic.'],
      ['Brokerage disclosures', 'Your brokerage name and licence details appear where your state requires them.'],
      ['Listing rights and accuracy', 'Only photos you have rights to, and details checked against the listing.'],
      ['Housing ad rules', 'Meta’s Housing ad category limits targeting by age, gender and postcode; ads are built within it.'],
    ],
    track: [
      ['Listing enquiries', 'Showing requests and messages about homes.'],
      ['Seller valuation requests', 'Future listings that started on social.'],
      ['Open-house RSVPs', 'From Stories and posts.'],
      ['Profile visits', 'From people in your area.'],
      ['Saves and shares of listings', 'Homes people are seriously considering.'],
    ],
    work: { ind: 'Real Estate', subs: [] },
    cases: null,
  },

  'social-media-management-for-salons': {
    name: 'salons and spas', noun: 'salon', people: 'clients', place: 'your chairs',
    cal: [
      ['Mon', 'Reel', 'Transformation of the week (client consent)', 'Before-and-after Reels are what clients book from.'],
      ['Wed', 'Carousel', 'This season’s colour trends', 'Inspiration people save for their next visit.'],
      ['Fri', 'Story', 'Last-minute openings', 'Fills gaps in the book.'],
      ['Mon', 'Reel', 'Meet your stylist', 'Clients follow stylists, not just salons.'],
      ['Wed', 'Carousel', 'Aftercare: make your colour last', 'Useful, and builds trust.'],
      ['Fri', 'Photo', 'Close-up detail shot', 'Shows the craft.'],
      ['Mon', 'Reel', 'A blow-out, start to finish', 'Satisfying process content holds attention.'],
      ['Wed', 'Carousel', 'Price guide: what’s included', 'Answers the question before the DM.'],
      ['Fri', 'Story', 'Poll: which look should we do next?', 'Engagement that shapes your content.'],
      ['Mon', 'Reel', 'The product we swear by, and how to use it', 'Expertise, and a reason to buy retail.'],
      ['Wed', 'Photo', 'A consented before-and-after', 'Proof of skill.'],
      ['Fri', 'Carousel', 'This month’s reviews', 'Social proof for new clients.'],
    ],
    platforms: [
      ['Instagram', 'Your portfolio', ['Transformations and stylist work', 'Stories with openings', 'A clear booking link']],
      ['TikTok', 'Where looks go viral', ['Transformations', 'Technique clips', 'Trends']],
      ['Google Business Profile', 'Where they book nearby', ['Photos of your work', 'Services and hours', 'Replies to reviews']],
      ['Pinterest', 'Where clients collect inspiration', ['Style boards linking to your booking page', 'Colour and cut ideas', 'Seasonal looks']],
    ],
    year: [
      ['New year, new look', 'Fresh-start bookings'], ['Valentine’s Day', 'Date-night styling'], ['Spring colour', 'Refreshes and brightening'],
      ['Prom season', 'Updos and trials'], ['Wedding season', 'Bridal parties and trials'], ['Summer cuts', 'Lighter styles'],
      ['Summer hair care', 'Sun and swim protection'], ['Back to school', 'Cuts for the new term'], ['Autumn colour', 'Warmer tones'],
      ['Halloween looks', 'Fun styling'], ['Holiday parties', 'Group and event bookings'], ['Gift cards & NYE', 'Gifts and New Year’s Eve looks'],
    ],
    rules: [
      ['Consent for every photo', 'Client photos and videos only with their OK.'],
      ['Every look credited', 'The stylist behind each look gets the credit.'],
      ['Real results, no filters', 'Nothing that changes how the hair or skin actually looks.'],
      ['Music cleared for business', 'Reels use audio licensed for business accounts.'],
    ],
    track: [
      ['Bookings from social', 'Appointments that started on Instagram or TikTok.'],
      ['Booking-link clicks', 'From posts, Stories and your profile.'],
      ['Saves on transformations', 'The looks people want.'],
      ['Profile visits', 'From people nearby.'],
      ['New clients mentioning social', 'At the chair, or in the booking form.'],
    ],
    work: { ind: 'Health & Beauty', subs: ['Hair & Barbers', 'Lashes & Nails', 'Skincare & Spa'] },
    cases: { label: 'health and beauty brands', slugs: ['natures-glow-emporium'] },
  },

  'social-media-management-for-car-dealerships': {
    name: 'car dealerships', noun: 'dealership', people: 'buyers', place: 'your lot',
    cal: [
      ['Mon', 'Reel', 'New arrival walkaround', 'Buyers want to see the car moving, not a stock photo.'],
      ['Wed', 'Carousel', 'Car of the week: the features that matter', 'Helps buyers compare before they visit.'],
      ['Fri', 'Story', 'Weekend test-drive slots', 'Turns browsing into a booked visit.'],
      ['Mon', 'Reel', 'Delivery day (with the buyer’s OK)', 'Happy buyers sell the next car.'],
      ['Wed', 'Carousel', 'How trade-in valuation works', 'Answers a question every buyer has.'],
      ['Fri', 'Photo', 'Meet the sales team', 'People buy from people.'],
      ['Mon', 'Reel', 'Service tip: what that dashboard light means', 'Brings service customers in, too.'],
      ['Wed', 'Carousel', 'Financing basics, with the required terms', 'Clear and compliant.'],
      ['Fri', 'Story', 'Poll: SUV or sedan?', 'Light engagement between inventory posts.'],
      ['Mon', 'Reel', 'Inside the service department', 'Trust for the long run.'],
      ['Wed', 'Carousel', 'The certified pre-owned checklist', 'Confidence for used-car buyers.'],
      ['Fri', 'Photo', 'Community event or sponsorship', 'Local dealerships win locally.'],
    ],
    platforms: [
      ['Facebook', 'Where local buyers shop', ['Inventory posts', 'Events and sales', 'Service offers']],
      ['Instagram', 'Where they fall for a car', ['Walkaround Reels', 'Delivery-day photos', 'Stories with new arrivals']],
      ['YouTube', 'Where they research models', ['Full walkarounds', 'Comparisons', 'Feature explainers']],
      ['Google Business Profile', 'Where they choose a dealer', ['Inventory and service posts', 'Hours for sales and service', 'Replies to reviews']],
    ],
    year: [
      ['New model year', 'Arrivals and first looks'], ['Tax refund season', 'Down-payment season'], ['Spring service', 'Tyres, checks and detailing'],
      ['Spring sales event', 'Inventory pushes'], ['Memorial Day', 'Sales weekend'], ['Road-trip ready', 'Service before summer'],
      ['Fourth of July', 'Sales weekend'], ['Model-year changeover', 'Outgoing models'], ['Labor Day', 'Sales weekend'],
      ['Winter prep', 'Tyres, batteries, service'], ['Black Friday', 'Offers and events'], ['Year-end sales', 'The last push of the year'],
    ],
    rules: [
      ['Price and finance disclosures', 'Advertised prices, APRs and payments carry the terms that the FTC and your state require.'],
      ['Financing ads, by the rules', 'Ads about credit run in Meta’s Credit ad category, which limits targeting.'],
      ['Inventory that’s really there', 'Posts are updated or removed when a car sells.'],
      ['Buyers’ consent', 'Delivery-day photos only with the buyer’s OK.'],
    ],
    track: [
      ['Leads', 'Forms, calls and messages from social.'],
      ['Test-drive bookings', 'Visits that started on social.'],
      ['Vehicle page views', 'Clicks through to specific cars.'],
      ['Service bookings', 'From service and maintenance posts.'],
      ['Local reach', 'Buyers in your area who saw your inventory.'],
    ],
    work: { ind: 'Professional Services', subs: ['Automotive'] },
    cases: null,
  },

  'social-media-management-for-coaches': {
    name: 'coaches and consultants', noun: 'business', people: 'clients', place: 'your calendar',
    cal: [
      ['Mon', 'Video', 'Your framework in 60 seconds', 'Shows how you think, which is what clients buy.'],
      ['Wed', 'Carousel', 'The framework, step by step', 'Saved and shared, so it keeps working.'],
      ['Fri', 'Post', 'A lesson from a client call (anonymised)', 'Real problems, real insight.'],
      ['Mon', 'Reel', 'A contrarian take on your field', 'Stands out in a crowded feed.'],
      ['Wed', 'Carousel', 'A client win (with permission)', 'Proof, told as a story.'],
      ['Fri', 'Story', 'Discovery-call slots', 'A clear next step.'],
      ['Mon', 'Video', 'One common question, answered', 'The FAQ your prospects have.'],
      ['Wed', 'Document', 'Deep dive: one problem, solved', 'LinkedIn documents build authority.'],
      ['Fri', 'Post', 'Behind the scenes of your work', 'Lets people know you before they hire you.'],
      ['Mon', 'Reel', 'Who this is for (and who it isn’t)', 'Attracts the right clients, repels the wrong ones.'],
      ['Wed', 'Carousel', 'A client journey, before and after', 'Makes the outcome tangible.'],
      ['Fri', 'Post', 'A free resource for your audience', 'Grows your email list.'],
    ],
    platforms: [
      ['LinkedIn', 'Where buyers check your authority', ['Insights and frameworks', 'Documents and case notes', 'Comments on your industry']],
      ['Instagram', 'Where people get to know you', ['Reels and Stories', 'Client wins', 'Behind the scenes']],
      ['YouTube', 'Where trust is built in depth', ['Longer teaching videos', 'Q&A', 'Talks and workshops']],
      ['TikTok and Shorts', 'Where new audiences find you', ['Quick takes', 'Myths in your field', 'Clips from longer videos']],
    ],
    year: [
      ['Goal-setting season', 'New-year planning'], ['Follow-through', 'Why goals stall in February'], ['Q1 review', 'What’s working, what isn’t'],
      ['Spring launch', 'New programmes and offers'], ['Mid-year plans', 'Resetting priorities'], ['Half-year review', 'Results and lessons'],
      ['Summer workshops', 'Lighter, shorter offers'], ['Back to business', 'September planning'], ['Q4 push', 'Finish the year strong'],
      ['Planning next year', 'Strategy content'], ['Year-end offers', 'Enrolment windows'], ['Year in review', 'Client wins and thank-yous'],
    ],
    rules: [
      ['No income or results guarantees', 'Earnings and results claims follow the FTC’s rules: typical results, not best cases.'],
      ['Testimonials with permission', 'Real clients who agreed, with disclosures for any incentive they received.'],
      ['Client details stay private', 'Stories are anonymised unless the client says otherwise.'],
      ['Partnerships disclosed', 'Paid partnerships and affiliate links are labelled.'],
    ],
    track: [
      ['Discovery-call bookings', 'Calls booked from social.'],
      ['Lead-magnet sign-ups', 'Email subscribers from your free resources.'],
      ['Profile visits', 'From your ideal clients.'],
      ['Comments and messages', 'Conversations with potential clients.'],
      ['Saves and shares', 'Content people keep and pass on.'],
    ],
    work: { ind: 'Professional Services', subs: ['Coaching & Consulting'] },
    cases: { label: 'education and professional services', slugs: ['client-c-vocational-training', 'client-b-high-acquisition-cost'] },
  },

  'social-media-management-for-ecommerce': {
    name: 'e-commerce brands', noun: 'store', people: 'customers', place: 'your checkout',
    cal: [
      ['Mon', 'Reel', 'The product in use, UGC style', 'Real-looking video sells better than polished ads.'],
      ['Wed', 'Carousel', 'This week’s bestsellers', 'Social proof in a swipe.'],
      ['Fri', 'Story', 'Restock or limited-stock alert', 'Urgency, honestly.'],
      ['Mon', 'Reel', 'How it’s made', 'Gives people a reason to pay more.'],
      ['Wed', 'Carousel', 'Customer reviews roundup', 'Answers “is it any good?”'],
      ['Fri', 'Story', 'Poll: which colour should we make next?', 'Customers help design the range.'],
      ['Mon', 'Reel', 'Three ways to use it', 'Shows more value from one product.'],
      ['Wed', 'Carousel', 'A gift guide', 'Shoppable and seasonal.'],
      ['Fri', 'Photo', 'A lifestyle shot', 'Helps people picture it in their life.'],
      ['Mon', 'Reel', 'Unboxing', 'The moment customers share.'],
      ['Wed', 'Carousel', 'Which product is right for you?', 'Helps undecided shoppers choose.'],
      ['Fri', 'Story', 'Last chance on an offer', 'A reminder before it ends.'],
    ],
    platforms: [
      ['Instagram', 'Where they discover and shop', ['Product Reels', 'Shoppable posts', 'Stories with offers']],
      ['TikTok', 'Where products go viral', ['UGC-style videos', 'TikTok Shop', 'Trends with your product']],
      ['Facebook', 'Where you bring them back', ['Retargeting people who visited your store', 'Catalogue ads', 'Customer community']],
      ['Pinterest', 'Where they plan purchases', ['Product pins linking to your store', 'Gift guides', 'Seasonal boards']],
    ],
    year: [
      ['New-year sales', 'And returns season'], ['Valentine’s Day', 'Gifts'], ['Spring launches', 'New collections'],
      ['Easter', 'Seasonal promotions'], ['Mother’s Day', 'Gifts'], ['Father’s Day', 'Gifts'],
      ['Mid-year sales', 'Summer sale events'], ['Back to school', 'Essentials'], ['Autumn collections', 'New season'],
      ['Halloween', 'And early holiday shopping'], ['Black Friday / Cyber Monday', 'The biggest weekend of the year'], ['Holiday gifting', 'And last shipping days'],
    ],
    rules: [
      ['Creators disclose', 'Paid and gifted creator posts are labelled, as the FTC’s endorsement guides require.'],
      ['Claims you can back up', 'Product claims, especially health and beauty ones, only when you can substantiate them.'],
      ['Rights to customer content', 'We ask permission before reposting customers’ photos and videos.'],
      ['Shop policies', 'Shoppable posts follow each platform’s commerce policies.'],
    ],
    track: [
      ['Purchases and return on ad spend', 'Sales that came from social, and what each dollar returned.'],
      ['Add-to-carts and link clicks', 'Shoppers moving towards checkout.'],
      ['Revenue by post and campaign', 'Which content actually sells.'],
      ['Email and SMS sign-ups', 'Customers you can reach again for free.'],
      ['Engagement on product Reels', 'Which products people want to see.'],
    ],
    work: { ind: 'Products', subs: null },
    cases: { label: 'e-commerce brands', slugs: ['client-a-ecommerce-scaling', 'client-d-mass-market-volume', 'tanseys', 'supplement-spot'] },
  },
};
