// Adds (or refreshes) the FX layer tags in every page's <head>.
// Idempotent: the block between the fx:start / fx:end markers is replaced.
//   node scripts/inject-fx.js           inject / update
//   node scripts/inject-fx.js --remove  strip the FX layer from every page
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const START = '<!-- fx:start -->';
const END = '<!-- fx:end -->';
const remove = process.argv.includes('--remove');

// Static markup from fx/partials/, placed at fixed points in <main>. Every page
// gets the pill nav (start of <main>) and the footer (end of <main>); the
// homepage also gets its own sections, each just before one of its React
// islands. Whatever they replace stays in the DOM (so React hydrates as usual)
// and is hidden by CSS (chrome.css, hero.css, hiw.css, portfolio.css,
// bottom.css).
const HOME = path.join(ROOT, 'index.html');
const BLOCKS = [
  { name: 'nav', at: 'main-start', files: ['nav.html'] },
  // Inner pages: the hero generated by scripts/build-heroes.js, before the island.
  { name: 'pagehero', at: 'first-island', files: [] },
  // Industry pages: their own sections, before and after the island
  // (scripts/build-industries.js).
  { name: 'industry-top', at: 'first-island', files: [] },
  { name: 'hero', home: true, island: 'FBHomeTop', files: ['home-hero.html'] },
  { name: 'hiw', home: true, island: 'FBHomeMain', files: ['home-trust.html', 'home-hiw.html', 'home-portfolio.html', 'home-pricing-head.html'] },
  // The case studies sit between the guarantee and "The real cost".
  { name: 'bottom', home: true, island: 'FBHomeBottom', files: ['home-bottom.html'], insert: { file: 'home-projects.html', before: '<section class="cx"' } },
  { name: 'shared', inner: true, at: 'main-end', files: [] },
  // Inner pages: their own cloned sections, rebuilt (scripts/build-sections.js).
  { name: 'sections', at: 'main-end', files: [] },
  { name: 'industry-bottom', at: 'main-end', files: [] },
  { name: 'footer', at: 'main-end', files: ['footer.html'] },
].map((b) => ({ ...b, start: `<!-- fx:${b.name}:start -->`, end: `<!-- fx:${b.name}:end -->` }));
const partial = (f) => fs.readFileSync(path.join(ROOT, 'fx', 'partials', f), 'utf8').trim();
// Inner pages: the old header sat in the flow, so keep its space under the nav.
const NAV_SPACE = '<div class="fx-navspace" aria-hidden="true"></div>';

// Inner pages repeat sections the homepage has rebuilt. Each page gets the
// rebuilt versions it needs in an inert <template>, and fx/shared.js swaps
// them in (keep these patterns in step with SWAPS there).
const SHARED = [
  { cls: 'tr', re: /publishing everywhere your customers/i },
  { cls: 'hw', re: /receive full deliverables/i },
  { cls: 'pf', re: /truly great content/i },
  { cls: 'gx', re: /not happy with your first batch/i },
  { cls: 'cx', re: /every other way costs more/i },
  { cls: 'pj', re: /real businesses\.\s*(<br\/?>)?\s*real results/i },
  { cls: 'rv', re: /real results, in their/i },
  // Final CTAs: the shared one, the page-specific card variants, and any
  // section with the "// begin" eyebrow every CTA variant opens with.
  { cls: 'ct', re: /ready to get social media off your plate|fill your calendar with booked jobs|ccta-card|fbe-cta-card|sbcta|pro-cta-card|rs-cta-card|>\s*\/\/\s*(<!--\s*-->)?\s*begin\s*</i },
];
// Pages whose own subject is one of these sections keep their original.
const KEEP = { reviews: ['rv'], 'case-studies': ['pj'] };
const LEGAL = ['privacy', 'refund', 'terms'];
const SHARED_CSS = ['projects.css', 'trust.css', 'hiw.css', 'portfolio.css', 'bottom.css'];
const sectionsOf = (file) => {
  const out = {};
  partial(file).split(/\n(?=<section class=")/).forEach((s) => {
    const m = s.match(/^<section class="([a-z]+)"/);
    if (m) out[m[1]] = s.trim();
  });
  return out;
};
function sharedFor(file, html) {
  const slug = path.relative(ROOT, path.dirname(file)).split(path.sep)[0];
  if (!slug || LEGAL.includes(slug)) return '';
  const body = html.slice(html.indexOf('<astro-island'));
  const all = Object.assign({}, ...['home-trust.html', 'home-hiw.html', 'home-portfolio.html', 'home-projects.html', 'home-bottom.html'].map(sectionsOf));
  // Service and category pages keep only the closing call to action (worded
  // for the page); the other shared sections are general, not about the
  // service. Industry pages build their own (none of these).
  const type = (html.match(/component-export="(ServicePage|CategoryPage|IndustryPage)"/) || [])[1];
  if (type === 'IndustryPage') return '';
  const want = SHARED.filter(({ cls, re }) => re.test(body) && !(KEEP[slug] || []).includes(cls) && all[cls] && (!type || cls === 'ct'));
  if (!want.length) return '';
  return `<template id="fx-shared">${want.map(({ cls }) => all[cls]).join('\n')}</template>`;
}

// Three.js is deliberately not preloaded: fx.js imports it on demand while the
// intro curtain plays, which keeps it off the critical path to DOMContentLoaded.
// The generated hero for an inner page ('' if none).
function heroFor(file) {
  const slug = path.relative(ROOT, path.dirname(file)).split(path.sep).join('__');
  const f = path.join(ROOT, 'fx', 'partials', 'heroes', slug + '.html');
  return slug && fs.existsSync(f) ? fs.readFileSync(f, 'utf8').trim() : '';
}

// Production build (scripts/build-fx.js): bundled, minified, content-hashed
// files in fx/dist/. Without it, pages load the sources directly.
const DIST = path.join(ROOT, 'fx', 'dist');
const MANIFEST = path.join(DIST, 'manifest.json');
const manifest = !remove && fs.existsSync(MANIFEST) ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) : null;
let esbuild = null;
try { esbuild = require('esbuild'); } catch (e) { /* stylesheets are joined but not minified */ }
const cssBundles = new Map();
// A page's stylesheets as one minified file (one request instead of up to ten).
function cssBundle(list) {
  const key = list.join('|');
  if (cssBundles.has(key)) return cssBundles.get(key);
  const src = list.map((f) => fs.readFileSync(path.join(ROOT, 'fx', f), 'utf8')).join('\n');
  const out = esbuild ? esbuild.transformSync(src, { loader: 'css', minify: true }).code : src;
  const name = `css-${require('crypto').createHash('sha256').update(out).digest('hex').slice(0, 10)}.css`;
  if (!fs.existsSync(path.join(DIST, name))) fs.writeFileSync(path.join(DIST, name), out);
  cssBundles.set(key, `/fx/dist/${name}`);
  return cssBundles.get(key);
}

// An inner page's rebuilt sections ('' if none): a <style> hiding the
// originals and a <template> that fx/sections.js swaps in.
function sectionsFor(file) {
  const slug = path.relative(ROOT, path.dirname(file)).split(path.sep).join('__');
  const f = path.join(ROOT, 'fx', 'partials', 'sections', slug + '.html');
  return slug && fs.existsSync(f) ? fs.readFileSync(f, 'utf8').trim() : '';
}

// Chrome / Edge: prerender a page when the pointer rests on its link, so the
// click shows it instantly.
const SPECULATION = '<script type="speculationrules">{"prerender":[{"where":{"and":[{"href_matches":"/*"},{"not":{"href_matches":"/login/*"}},{"not":{"selector_matches":"[target=_blank], [download]"}}]},"eagerness":"moderate"}]}</script>';

// An industry page's own sections: { top, bottom } (null if not one).
function industryFor(file) {
  const slug = path.relative(ROOT, path.dirname(file)).split(path.sep).join('__');
  const f = (part) => path.join(ROOT, 'fx', 'partials', 'industry', `${slug}.${part}.html`);
  return slug && fs.existsSync(f('top')) ? { top: fs.readFileSync(f('top'), 'utf8').trim(), bottom: fs.readFileSync(f('bottom'), 'utf8').trim() } : null;
}

function block(home, shared, hero, nx, ind) {
  const css = [
    'fx.css',
    'chrome.css',
    ...(home || /class="hx /.test(hero) ? ['hero.css'] : []),
    ...(/class="ph/.test(hero) ? ['ph.css'] : []),
    ...(/class="csx/.test(hero) ? ['cases.css'] : []),
    ...(home || shared ? SHARED_CSS : []),
    ...(nx || ind ? ['nx.css', 'ind.css'] : []),
    ...(ind && !shared ? ['bottom.css'] : []),
  ];
  const font = '<link rel="preload" href="/fonts/instrument-serif-latin-400-italic.woff2" as="font" type="font/woff2" crossorigin>';
  if (manifest) {
    return [
      START,
      `<link rel="stylesheet" href="${cssBundle(css)}">`,
      font,
      // Homepage: the hero phone's poster is the biggest thing on a phone's first screen.
      ...(home ? ['<link rel="preload" as="image" href="/fx/media/hero-phone.webp" fetchpriority="high">'] : []),
      `<script>${manifest.boot}</script>`,
      `<script src="${manifest.vendor}" defer></script>`,
      ...manifest.eager.map((c) => `<link rel="modulepreload" href="${c}">`),
      `<script type="module" src="${manifest.js}"></script>`,
      SPECULATION,
      END,
    ].join('\n');
  }
  return [
    START,
    ...css.map((f) => `<link rel="stylesheet" href="/fx/${f}">`),
    font,
    '<script src="/fx/boot.js"></script>',
    '<script src="/fx/vendor/gsap.min.js" defer></script>',
    '<script src="/fx/vendor/ScrollTrigger.min.js" defer></script>',
    '<script src="/fx/vendor/lenis.min.js" defer></script>',
    '<script type="module" src="/fx/fx.js"></script>',
    END,
  ].join('\n');
}

function pages(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.') || entry.name === 'fx') continue;
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) pages(p, out);
    else if (entry.name.endsWith('.html')) out.push(p);
  }
  return out;
}

let changed = 0;
// Standalone pages with their own markup and styles (no React, no FX layer).
const STANDALONE = ['login'];
for (const file of pages(ROOT)) {
  if (STANDALONE.includes(path.relative(ROOT, path.dirname(file)).split(path.sep).join('/'))) continue;
  const src = fs.readFileSync(file, 'utf8');
  let html = src;
  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a !== -1 && b !== -1) html = html.slice(0, a).replace(/\n$/, '') + html.slice(b + END.length).replace(/^\n/, '');
  const home = file === HOME;
  for (const blk of BLOCKS) {
    const s = html.indexOf(blk.start);
    const e = html.indexOf(blk.end);
    if (s !== -1 && e !== -1) html = html.slice(0, s) + html.slice(e + blk.end.length);
  }
  if (!remove) {
    const i = html.indexOf('</head>');
    if (i === -1) { console.warn('no </head>:', path.relative(ROOT, file)); continue; }
    const shared = home ? '' : sharedFor(file, html);
    const hero = home ? '' : heroFor(file);
    const nx = home ? '' : sectionsFor(file);
    const ind = home ? null : industryFor(file);
    html = html.slice(0, i) + '\n' + block(home, !!shared, hero, !!nx, !!ind) + '\n' + html.slice(i);
    for (const blk of BLOCKS) {
      if (blk.home && !home) continue;
      if (blk.inner && (home || !shared)) continue;
      if (blk.name === 'pagehero' && !hero) continue;
      if (blk.name === 'sections' && !nx) continue;
      if (blk.name.startsWith('industry') && !ind) continue;
      let k = -1;
      if (blk.at === 'main-start') {
        const m = html.indexOf('<main');
        k = m === -1 ? -1 : html.indexOf('>', m) + 1;
      } else if (blk.at === 'first-island') {
        k = html.indexOf('<astro-island', html.indexOf('<main'));
      } else if (blk.at === 'main-end') {
        k = html.lastIndexOf('</main>');
      } else {
        const at = html.indexOf(`component-export="${blk.island}"`);
        k = at === -1 ? -1 : html.lastIndexOf('<astro-island', at);
      }
      if (k <= 0) { console.warn(`no place for ${blk.name}:`, path.relative(ROOT, file)); continue; }
      const extra = blk.name === 'nav' && !home && !hero ? NAV_SPACE : blk.name === 'shared' ? shared : blk.name === 'pagehero' ? hero : blk.name === 'sections' ? nx : blk.name === 'industry-top' ? ind.top : blk.name === 'industry-bottom' ? ind.bottom : '';
      let body = blk.files.map(partial).join('\n');
      if (blk.insert) {
        const at = body.indexOf(blk.insert.before);
        if (at === -1) console.warn(`no "${blk.insert.before}" in ${blk.name}`);
        else body = body.slice(0, at) + partial(blk.insert.file) + '\n' + body.slice(at);
      }
      html = html.slice(0, k) + blk.start + body + extra + blk.end + html.slice(k);
    }
  }
  if (html !== src) {
    fs.writeFileSync(file, html);
    changed++;
  }
}
console.log(`${remove ? 'removed from' : 'injected into'} ${changed} page(s)`);
